services:
  - type: web
    name: streamlit-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PORT
        value: 8501
